### ISSUE TITLE
Inconsistency with Apple Documentation

### ISSUE THREAD

**Issue by soberman** [github/objective-c-style-guide#60]
In Declarations section you have a point about struct initializers. You state, that it is preferable to use C99 style syntax to Apple helper functions. However, it is clearly stated in Apple documentation, that is not recommended to directly write to CGRect structs and others.

[Apple CGGeometry Reference](https://developer.apple.com/library/ios/documentation/GraphicsImaging/Reference/CGGeometry/#//apple_ref/c/func/CGVectorMake)
> All functions described in this reference that take CGRect data structures as inputs implicitly standardize those rectangles before calculating their results. For this reason, your applications should avoid directly reading and writing the data stored in the CGRect data structure. Instead, use the functions described here to manipulate rectangles and to retrieve their characteristics.

**Comment by joshaber** [comment]
Yeah, that's probably worth changing. A PR would be great :+1:
