### ISSUE TITLE
Why "The contents of array and dictionary literals should have a space on both sides."?

### ISSUE THREAD

**Issue by Coeur** [github/objective-c-style-guide#65]
What about an empty array/dictionary?

    @[ ]; @{ };

Or:

    @[]; @{};

What about [boxed expressions](http://clang.llvm.org/docs/ObjectiveCLiterals.html#boxed-expressions)?

    @( M_PI / 2 ); @( view.frame );

Or:

    @(M_PI / 2); @(view.frame);

When you write `@property (nonatomic)` or `if (a == b)` you don't put spaces on both sides of the content, so I don't get the point to put spaces for array and dictionary literals.

**Comment by joshaber** [comment]
The motivation was to try to disambiguate method calls vs. array literals:

```objc
[someObject doThing];
```
vs.
```objc
@[someObject doThing];
```

The cases you cite don't have that problem.

**Comment by codiophile** [comment]
@joshaber Your example does not make any sense. The second line is not even valid objective-c. You don't need a coding standard to differentiate between valid and invalid objective-c, the compiler will do that for you. The relevant example would be:

    [someObject doThing];

vs.

    @[someObject, doThing];

vs. 

    @[ someObject, doThing ];

I think the OP is making a good case for consistency and that someone could fail to see an at-sign and a comma in a declaration of a two element array and confuse it with a method invocation, is a very poor counter argument.

**Comment by robb** [comment]
I think it's worth remembering that these style guides are descriptive, rather than prescriptive and that this is just what the GH came to agree on.

**Comment by joshaber** [comment]
Indeed. There's not much more to be said.
