### ISSUE TITLE
Referencing https://google.github.io/styleguide/objcguide.xml as well

### ISSUE THREAD

**Issue by Coeur** [github/objective-c-style-guide#66]
Document is referencing https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/CodingGuidelines/CodingGuidelines.html at top only. Using https://google.github.io/styleguide/objcguide.xml as well would be nice.

**Comment by joshaber** [comment]
Well, we reference that because that is what we've built off of. We haven't looked at or used the Google guide. :smile:
